# Dependencies
markdown:         kramdown


# Permalinks
permalink:        pretty

# Setup
title:            Shervin Khazaeli
tagline:          ''
description:      ''
url:              http://website.github.io


github_username:  ModernCan
permalink: /:year/:month/:title.html
excerpt_separator: <!--more-->



# Dependencies
gems:                [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
